/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.util.Date;
//import com.itextpdf.text.Document;
//import com.itextpdf.text.DocumentException;
//import com.itextpdf.text.Element;
//import com.itextpdf.text.FontFactory;
//import com.itextpdf.text.Image;
//import com.itextpdf.text.PageSize;
//import com.itextpdf.text.Paragraph;
//import com.itextpdf.text.Rectangle;
//import com.itextpdf.text.pdf.PdfDocument;
//import com.itextpdf.text.pdf.PdfPCell;
//import com.itextpdf.text.pdf.PdfPTable;
//import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Swetha
 */
public class Project extends javax.swing.JFrame{

    /**
     * @param args the command line arguments
     */
      public Project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("rollno");

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("semester");

        jButton2.setText("verify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("name");

        jLabel4.setText("fail");

        jLabel5.setText("absent");

        jLabel6.setText("oops");

        jLabel7.setText("dpsd");

        jLabel8.setText("coa");

        jLabel9.setText("ds");

        jLabel10.setText("maths");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(93, 93, 93)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(114, 114, 114)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(361, 361, 361)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(367, 367, 367)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButton2)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(jTextField8)
                        .addComponent(jTextField7)
                        .addComponent(jTextField6)
                        .addComponent(jTextField5)
                        .addComponent(jTextField10))
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(357, 357, 357))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(75, 75, 75)
                .addComponent(jButton1)
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        try {
            
            
           // ResultSet s=st.executeQuery("select * from A where rollno='"+r+"'");
           
                   Document d=new Document(PageSize.LETTER);
          
            PdfWriter.getInstance(d,new FileOutputStream(new File("demo1.pdf")));
            Image i=Image.getInstance("C:\\Users\\Swetha\\Documents\\NetBeansProjects\\project\\src\\project\\clg logo.jpg");
            i.setAbsolutePosition(4,680);
            i.scaleToFit(100,100);
            d.open();
            d.add(i);
            Paragraph p=new Paragraph("           VELAMMAL COLLEGE OF ENGINEERING AND TECHNOLOGY",FontFactory.getFont(FontFactory.TIMES_BOLD,13f));
            p.setAlignment(Element.ALIGN_CENTER);
            d.add(p);
            d.add(new Paragraph("                                                              (Autonomous) \n",FontFactory.getFont(FontFactory.TIMES_BOLD,12f)));
            d.add(new Paragraph("                               DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING",FontFactory.getFont(FontFactory.TIMES_BOLD,13f)));
            d.add(new Paragraph("    ______________________________________________________________________________"));
            d.add(new Paragraph("    VCET/CSE/2022-23/EXAMCELL					   	                            Date:"+ new Date().toString(),FontFactory.getFont(FontFactory.TIMES_BOLD,12f)));
            d.add(new Paragraph("      Sub: Performance of your ward in "+jTextField3.getText()+" Semester Examination,  B.E./B.Tech. II/III  year –Reg.",FontFactory.getFont(FontFactory.TIMES_BOLD,12f)));
            d.add(new Paragraph("      This letter brings to your notice that your ward Mr./Ms. "+jTextField4.getText()));
            d.add(new Paragraph("      Roll No "+jTextField1.getText()+" studying in B.E.CSE has failed/Absent in "+jTextField2.getText()+" Subjects "));
            d.add(new Paragraph("      "+jTextField3.getText()+" Semester Examination conducted"));
            //d.add(new Paragraph("      in the ___________________up to_________________"));
           //d.add(new Paragraph("                      "));
            d.add(new Paragraph("      You may be aware, achieving academic excellence is very much essential for getting placement"));
            d.add(new Paragraph("      and shaping the future career of your ward. You are therefore, requested to bestow your  "));
            d.add(new Paragraph("      attention in the education of your ward, which not only make him/her competent but also be a"));
            d.add(new Paragraph("      source of strength to the family and the society."));
         //   d.add(new Paragraph("                                                                                                                    "));
            d.add(new Paragraph("      you are requested to take utmost care in your ward’s progress in achieving pass and scoring")); 
            d.add(new Paragraph("      good marks in all the subjects in the forthcoming Internal Assessment & Model Examination."));
         //   d.add(new Paragraph("                                                                                                                     "));
            d.add(new Paragraph("      Each Internal Assessment carries marks in the calculation of internal marks. Totally 20 marks are "));
            d.add(new Paragraph("      in stake for each Internal Assessment, which may decide the Cumulative Grade (I /II class)"));
            d.add(new Paragraph("      at the end of the program and at the placement."));
          //  d.add(new Paragraph("                                                                                                                        "));
            d.add(new Paragraph("      In this connection you are required to meet the HOD to discuss about you ward’s " ,FontFactory.getFont(FontFactory.TIMES_BOLD,12f)));
            d.add(new Paragraph("      performance on or before 28/9/2022 between 2.00 pm to 3.00 pm without fail, otherwise the  ",FontFactory.getFont(FontFactory.TIMES_BOLD,12f)));
            d.add(new Paragraph("      student will not be allowed to attend the class from:\n",FontFactory.getFont(FontFactory.TIMES_BOLD,12f) ));    
            d.add(new Paragraph("                                                                                                                        "));
            d.add(new Paragraph("                                                                                                                        "));
          
             PdfPTable  t=new PdfPTable(3);
             float a[]={50f,300f,100f};
             t.setTotalWidth(a);
          Connection c= c = DriverManager.getConnection("jdbc:derby://localhost:1527/projectdb");
             java.sql.Statement st= c.createStatement();
                String r=jTextField1.getText();
         
            ResultSet rs=st.executeQuery("select * from semresult where rollno='"+jTextField1.getText()+"'");
            
                PdfPCell c1=new PdfPCell(new Paragraph("Course Title"));
                 PdfPCell c2=new PdfPCell(new Paragraph("SI.NO"));
                PdfPCell c3=new PdfPCell(new Paragraph(jTextField3.getText()+" SEMESTER"));
                
                 t.addCell(c1);
                  t.addCell(c2);
                  t.addCell(c3);
                
           while(rs.next())
           {
               
                PdfPCell c4=new PdfPCell(new Paragraph(" 1"));
                PdfPCell c5=new PdfPCell(new Paragraph("Object Oriented Programming"));
                PdfPCell c6=new PdfPCell(new Paragraph(" "+rs.getString("oops")));
                PdfPCell c7=new PdfPCell(new Paragraph(" 2"));
                PdfPCell c8=new PdfPCell(new Paragraph("Discrete Mathematics"));
                PdfPCell c9=new PdfPCell(new Paragraph(" "+rs.getString("mat")));
                PdfPCell c10=new PdfPCell(new Paragraph(" 3"));
                PdfPCell c11=new PdfPCell(new Paragraph("Computer Organization and Architecture "));
                PdfPCell c12=new PdfPCell(new Paragraph(" "+rs.getString("coa")));
                PdfPCell c13=new PdfPCell(new Paragraph(" 4"));
                PdfPCell c14=new PdfPCell(new Paragraph("Digital Principle and System Design"));
                PdfPCell c15=new PdfPCell(new Paragraph(" "+rs.getString("dpsd")));
                PdfPCell c16=new PdfPCell(new Paragraph(" 5"));
                PdfPCell c17=new PdfPCell(new Paragraph("Data Structure0"));
                PdfPCell c18=new PdfPCell(new Paragraph(" "+rs.getString("ds")));
                  
                 
                  t.addCell(c4);
                  t.addCell(c5);
                  t.addCell(c6);
                  t.addCell(c7);
                  t.addCell(c8);
                  t.addCell(c9);
                  t.addCell(c10);
                  t.addCell(c11);
                  t.addCell(c12);
                  t.addCell(c13);
                  t.addCell(c14);
                  t.addCell(c15);
                  t.addCell(c16);
                  t.addCell(c17);
                  t.addCell(c18);
                 d.add(t);
                  
            }
            
              d.add(new Paragraph("                                                                                                                        "));
              d.add(new Paragraph("                                                                                                                        "));
              d.add(new Paragraph("                                                                                                                        "));
              d.add(new Paragraph("                                                                                                                        "));
          d.add(new Paragraph("                 Class In Charge                                                                        HOD/CSE",FontFactory.getFont(FontFactory.TIMES_BOLD,13f)));
         
         JOptionPane.showMessageDialog(null,"generated");
            d.close();
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           Connection c;
        try {
            c = c = DriverManager.getConnection("jdbc:derby://localhost:1527/projectdb");
             java.sql.Statement st= c.createStatement();
                 ResultSet rs=st.executeQuery("select * from semresult where rollno='"+jTextField1.getText()+"'");
                 while(rs.next())
                 {
                       jTextField4.setText(rs.getString("name"));
                        jTextField6.setText(rs.getString("oops"));
                         jTextField7.setText(rs.getString("dpsd")); 
                          jTextField8.setText(rs.getString("coa"));
                          jTextField9.setText(rs.getString("ds"));
                           jTextField10.setText(rs.getString("mat"));
                         if(rs.getString("oops").equals("u"))
                         {
                             jTextField2.setText("oops");
                         }
                         if(rs.getString("dpsd").equals("u"))
                         {
                             jTextField2.setText("dpsd");
                         }
                         if(rs.getString("coa").equals("u"))
                         {
                             jTextField2.setText("coa");
                         }
                         if(rs.getString("ds").equals("u"))
                         {
                             jTextField2.setText("ds");
                         }
                         if(rs.getString("mat").equals("u"))
                         {
                             jTextField2.setText("mat");
                         }
                         
                 }
           
        } catch (SQLException ex) {
            Logger.getLogger(Project.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    }
    

